=== TechSysApi/cen-sortplan-dist/model/json-schema-v3-full/special-sort-table.json
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "definitions": {},
  "type": "object",
  "properties": {
    "timestamp": {
      "type": "string",
      "description": "The date+timstamp which identifies the point in time, where the information was generated, including milliseconds.",
      "format": "date-time",
      "required": true
    },
    "name": {
      "type": "string",
      "description": "The name of the special sort table\nFormat: tablename.key.timestamp\nExample: SPECIALVZ.201446.20180222100409 ",
      "maxLength": 40,
      "required": true
    },
    "sortingProducts": {
      "type": "array",
      "items": {
        "$schema": "http://json-schema.org/draft-03/schema#",
        "definitions": {},
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the sorting product. ",
            "required": true
          },
          "specialSorts": {
            "type": "array",
            "items": {
              "$schema": "http://json-schema.org/draft-03/schema#",
              "definitions": {},
              "type": "object",
              "properties": {
                "name": {
                  "description": "The name of the special sort. ",
                  "required": true,
                  "$schema": "http://json-schema.org/draft-03/schema#",
                  "definitions": {},
                  "type": "string",
                  "enum": [
                    "UNKNOWN",
                    "OK",
                    "MAX_RECIRCULATION",
                    "ITEM_NO_READ",
                    "ITEM_MULTIPLE_READ",
                    "SCANNER_TIMEOUT",
                    "ITEM_STRAY",
                    "ITEM_INDUCTION_ERROR",
                    "ITEM_DISCHARGE_ERROR",
                    "ITEM_ERROR",
                    "ITEM_TRACKING_ERROR",
                    "ITEM_OCCUPIED_TWICE_ERROR",
                    "ITEM_DISAPPEARED",
                    "OUTLET_NOT_AVAILABLE",
                    "OUTLET_UNKNOWN",
                    "UNDEFINED_ERROR",
                    "NO_CAPACITY",
                    "DIMENSION_ERROR",
                    "WEIGHT_ERROR",
                    "SORTPLAN_ERROR",
                    "DIRECT_SORTING_MODE",
                    "ITEM_NO_SORTCODE",
                    "OUTLET_MISSED"
                  ],
                  "id": "SortReason"
                }
              },
              "additionalProperties": false,
              "description": "Special logistics and technical destinations. Typical examples are “REJECT” or “OVERFLOW”.",
              "id": "SpecialSort"
            },
            "description": "Special logistics and technical destinations. Typical examples are “REJECT” or “OVERFLOW”."
          }
        },
        "additionalProperties": false,
        "description": "Sorting product describes \"what the machine produces\". This is typically the content of an Outlet. \nThe sorting product can be are logistics destinations and special sorts",
        "id": "SortingProduct"
      },
      "minItems": 1,
      "required": true
    },
    "actions": {
      "type": "array",
      "items": {
        "$schema": "http://json-schema.org/draft-03/schema#",
        "definitions": {},
        "type": "object",
        "properties": {
          "sortingProduct": {
            "type": "string"
          },
          "sorts": {
            "type": "array",
            "items": {
              "$schema": "http://json-schema.org/draft-03/schema#",
              "definitions": {},
              "type": "object",
              "properties": {
                "outletGroup": {
                  "type": "integer",
                  "description": "A reference on the name of the outlet group. \nDas Virtuelle Ziel fasst eine Liste von Endstellen zu einem logischen Sortierziel, auch Endstellengruppe genannt, zusammen.",
                  "maxLength": 3,
                  "required": true
                },
                "position": {
                  "type": "integer",
                  "description": "Die Endstellen-Position dient zum Positionieren der Anzeige auf dem Display der Endstelle und hat die Bedeutung des Rx-Stellplatzes an der Endstelle.\nDie Endstellen-Position ist eine bis zu einstellige positive Zahl. Eine Endstellengruppe hat max. neun Positionen.",
                  "minimum": 1,
                  "maxLength": 1
                }
              },
              "additionalProperties": false,
              "description": "Sort/sequence this product to an OutletGroup. For dynamic outletGroups\nspecify the relative position withing Group",
              "id": "Sort"
            }
          },
          "prints": {
            "type": "array",
            "items": {
              "$schema": "http://json-schema.org/draft-03/schema#",
              "definitions": {},
              "type": "object",
              "properties": {
                "location": {
                  "description": "Specifies the print Location i.e. where action is performed. Typical locations\nare Label-Printer or Display.",
                  "required": true,
                  "$schema": "http://json-schema.org/draft-03/schema#",
                  "definitions": {},
                  "type": "string",
                  "enum": [
                    "UNKNOWN",
                    "LABEL_PRINTER",
                    "DISPLAY"
                  ],
                  "id": "LocationType"
                },
                "format": {
                  "type": "string",
                  "description": "Text zur Anzeige auf dem Display der Endstelle\nBeispiele: Bezirk/Tour, Plz, Rx-Stellplatz, Zielzentrum",
                  "maxLength": 20,
                  "required": true
                }
              },
              "additionalProperties": false,
              "description": "Describes what shall be printed on a label or a display for mail\nitems that fall into a given Product.",
              "id": "Print"
            }
          }
        },
        "additionalProperties": false,
        "description": "Maps a product to an action.",
        "id": "Action"
      },
      "minItems": 1,
      "required": true
    }
  },
  "additionalProperties": false,
  "id": "SpecialSortTable"
}

=== TechSysApi/cen-sortplan-dist/v1.1.9/samples/generated-SpecialSortTable.json
{
    "timestamp": "2018-03-05T15:11:28.000Z",
    "name": "SPECIALVZ.201446.20180222100409",
    "sortingProducts": [{
        "name": "799",
        "specialSorts": [{
            "name": "ITEM_NO_READ"
        }, {
            "name": "ITEM_MULTIPLE_READ"
        }, {
            "name": "ITEM_STRAY"
        }, {
            "name": "ITEM_INDUCTION_ERROR"
        }, {
            "name": "ITEM_DISCHARGE_ERROR"
        }, {
            "name": "ITEM_ERROR"
        }, {
            "name": "ITEM_TRACKING_ERROR"
        }, {
            "name": "ITEM_OCCUPIED_TWICE_ERROR"
        }, {
            "name": "ITEM_DISAPPEARED"
        }]
    }, {
        "name": "899",
        "specialSorts": [{
            "name": "MAX_RECIRCULATION"
        }, {
            "name": "SCANNER_TIMEOUT"
        }, {
            "name": "OUTLET_NOT_AVAILABLE"
        }, {
            "name": "OUTLET_UNKNOWN"
        }, {
            "name": "UNDEFINED_ERROR"
        }, {
            "name": "NO_CAPACITY"
        }, {
            "name": "DIMENSION_ERROR"
        }, {
            "name": "WEIGHT_ERROR"
        }, {
            "name": "SORTPLAN_ERROR"
        }, {
            "name": "DIRECT_SORTING_MODE"
        }]
    }],
    "actions": [{
        "sortingProduct": "799",
        "sorts": [{
            "outletGroup": 799
        }]
    }, {
        "sortingProduct": "899",
        "sorts": [{
            "outletGroup": 899
        }]
    }]
}
